services:
  db:
    # (windows + docker desktop + wsl2 + mariadb + bookstack) is initial migration failed.
    # mysql is used as an alternative for samples.
    image: mysql:8
    restart: unless-stopped
    networks:
      default:
        aliases:
          - bookstack-db-container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s
    ports:
      - "9983:3306"
    volumes:
#      - ../volumes/db:/var/lib/mysql
      - ./assets:/dummy-mount:ro
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=bookstack_rootpass
      - MYSQL_DATABASE=bookstack_store
      - MYSQL_USER=bookstack_user
      - MYSQL_PASSWORD=bookstack_pass

  app:
    image: lscr.io/linuxserver/bookstack:version-v23.06.1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:
        aliases:
          - bookstack-app-container
    ports:
      - "9984:80"
    volumes:
#      - ../volumes/app/config:/config
      - ../volumes/app/localize/lang:/app/www/lang
      - ../volumes/app/localize/views:/app/www/resources/views
      - ./assets/init:/custom-cont-init.d
      - ./assets/template:/assets/template
    environment:
      - TZ=Asia/Tokyo
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:9984/
      - DB_HOST=bookstack-db-container
      - DB_DATABASE=bookstack_store
      - DB_USER=bookstack_user
      - DB_PASS=bookstack_pass
      - CUSTOM_APP_THEME=my-theme
      - CUSTOM_API_REQUESTS_PER_MIN=99999
      - CUSTOM_MAIL_HOST=localize-host-gateway
      - CUSTOM_MAIL_PORT=1025
      - CUSTOM_MAIL_ENCRYPTION=null
    extra_hosts:
          - localize-host-gateway:host-gateway

