services:
  db:
    volumes:
      - ../volumes/db:/var/lib/mysql

  app:
    volumes:
      - ../volumes/app/localize/lang:/app/www/lang
      - ../volumes/app/localize/views:/app/www/resources/views
      - ../volumes/app:/config
